runner: "research.muP_MoE.train.train"

# time: "05:00:00"
time: "00:10:00"

n_gpus: 1
cpus_per_gpu: 16

interactive_debug: false

params:
  name: "muP_MoE_10_step_new"
  # tags: ["muP_MoE", "muTransfer", "norm_plot_3"]
  tags: ["muP_MoE", "muTransfer", "10_step_new"]

  mup_params:
    ^alpha_in: [10.0]
    ^alpha_out: [0.1]
    # alpha_in: 5.0
    # alpha_out: 0.2
    base_dmodel: 256

  # training
  n_steps: 10
  lr_warmup_steps: 0
  batch_size: 64
  cutoff: 256

  # model
  model_type: gpt
  # dmodel: 32
  # ^dmodel: [256, 384, 512, 768, 1024, 1536, 2048, 3072, 4096]
  ^dmodel: [256, 384, 512, 768, 1024]
  ^n_blocks: [2]
  dhead: 64
  attention_mode: 'vanilla'
  attention_normalization: 'dhead'
  use_torch_bmm: true

  ff_mode: vanilla
  dff_ratio: 4

  # MoE aux losses
  load_balancing_loss_weight: 0.01
  zloss_weight: 0.001


  # learning
  scheduler: constant
  learning_rate: 1e-3
  final_lr_fraction: 0.1
  grad_clip: 1
  weight_decay: 0.1
  ^init_scale: [0.001]
  init_type: truncated_normal
  capacity_factor: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.95

  # FSDP
  # fsdp_enabled: true
  # fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,Attention,ExpertFF,TokenGating"
  # activation_checkpointing_modules: "EmbeddingLayer,PredictionHead,TransformerBlock"
  # fsdp_selective_precision_modules: "AttentionMechanism,RoPE"

  # other
  dataset_type: c4
  mixed_precision: true
  flash_attention: true
  mixed_precision_dtype: bfloat16
  ^data_seed: [205, 206, 207, 208, 209]

  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 1
  # logging_interval_light: 50
  # logging_interval_loss: 20
  # save_weights_interval: null
  print_parameter_names: true

  # debug
  # logger_types: "stdout"
  # n_steps: 100
  # batch_size: 8
  # cutoff: 16
  # use_dummy_dataset: true
  # n_blocks: 2
  # dmodel: 16
  # n_att_heads: 2
