parent: configs/baselines/gpt/grad_norm/common.yml
md5_parent_hash: fcbfaf83d757cd20c85acd2ffff7517f
time: 2-00:00:00

params:
  name: "grad_norm_base"
  dmodel: 768
  n_blocks: 12
  n_att_heads: 12
  dff: 3072
