# grid args
runner: "research.conditional.train.cc_train"
time: "0-10:00:00"
n_gpus: 1

# train params
params:
  # model
  batch_size: 4
  cutoff: 16
  project_name: "pmtest/llm-random-tests"
  name: "baseline_test"
  mixed_precision: true
  tags:
    - "test"
  use_neptune: true
  n_steps: 1000
  dmodel: 64
  dff: 256
  n_blocks: 2
  "^model_type":
    - "bert"
  "^ff_mode":
    - "vanilla"
  logging_interval_heavy: 2
  logging_interval_loss: 1
  grad_clip: 0.5
  scheduler: constant
  lr_warmup_steps: 100
  learning_rate: 0.0001
  final_lr_step: 900
  final_lr_fraction: 0.1
  n_att_heads: 4
  dataset_type: wikibook
  use_dummy_dataset: true
