time: "2-00:00:00"
n_gpus: 1
interactive_debug: false

# train params
params:
  # base bass
  mixed_precision: true

  # logging etc.
  use_neptune: true
  project_name: "pmtest/llm-random"
  name: "f-bench"
  logging_interval_heavy: 5000
  logging_interval_loss: 1000
  save_weights_path: "model_ckpt"
  save_weights_interval: 25_000

  # shallower bass
  cutoff: 256
  batch_size: 256
  n_steps: 275_000
  lr_warmup_steps: 12_500 # <- rewrite scheduling
  lr_decay_interval: 1 # <- rewrite scheduling
  lr_decay: 0.9999777 # <- rewrite scheduling

  grad_clip: 0.5
