# grid args
runner: "research.conditional.train.cc_train"
time: "48:00:00"
n_gpus: 1
interactive_debug: false

# train params
params:
  # model
  model_type: "gpt"
  dataset_type: "c4"
  dmodel: 512
  dff: 2048
  n_att_heads: 8
  n_blocks: 4
  cutoff: 256
  batch_size: 256
  loss_checkpoint_chungs: 64

  n_steps: 270000
  grad_clip: 0.5
  lr_decay: 0.9999777
  lr_warmup_steps: 10000
  lr_decay_interval: 1

  logging_interval_heavy: 1000
  logging_interval_loss: 1000

  save_weights_path: "weights_gpt_dense_small"
  save_weights_interval: 50000

  use_neptune: true
  project_name: "pmtest/llm-random"
  name: "gpt_small_dense_baseline"
  mixed_precision: true
  tags:
    - "gpt"
    - "dense_baseline"
    - "small"

