parent: research/conditional/train/configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 17e23fa8efdf44ed2a84b8e15941039c
interactive_debug: false
n_gpus: 8
time: "30:00:00" # this is for entropy

singularity_image:  /local_storage_1/sparsity_2023.12.14_16.44.42.sif # entropy
hf_datasets_cache: /local_storage_1/dataset_cache # entropy

params:
    general_ff_layer_config: "vanilla,vanilla,vanilla,vanilla,vanilla,vanilla,moe_chimera,moe_chimera,moe_chimera,moe_chimera,moe_chimera,moe_chimera"


    n_steps: 200_000
    final_lr_step: 200_000
    chimera_schedule: 2
    #name
    name: mot_to_switch_transition_tuning_base_please
    tags: [mot,switch,chimera]

    #mot
    group_size: 32
    n_experts: 32
    flop_matched: true
    sparsity_dim: 0
    temperature: 1.0

    #switch
    load_balancing_loss_weight: 0.01
    capacity_factor: 1.25
    expert_size: 3072


    #tuning
    learning_rate: 2e-4
    init_type: truncated_normal
    init_scale: 0.1
    weight_decay: 0.1

    #data
    batch_size: 256
    dataset_type: c4

    #eval and logging

    log_gradients_and_weights: false
    decoding_interval: 0
    logging_interval_heavy: 1000
    eval_interval: 1000
    save_weights_interval: 0

    #fsdp
    fsdp_enabled: true
    fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
    fsdp_selective_precision_modules: "AttentionMechanism"

    #throughput
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: false
    gradient_accumulation_steps: 1
    loss_checkpoint_chungs: 8