
parent: research/conditional/train/configs/baselines/gpt/dense/medium.yaml
md5_parent_hash: 7a0330388646a9bfbcbee67008f9538a
interactive_debug: false
n_gpus: 1
cuda_visible: "0"
time: "48:00:00"
params:
    n_steps: 100000

    #name
    name: baseline_mot_medium
    tags: [mot, sigm, swish]

    ff_mode: cont_moe

    group_size: 32
    n_experts: 32
    flop_matched: true
    sparsity_dim: 0
    temperature: 1.0


    #tuning
    ^learning_rate: [ 5e-5, 1e-4, 2e-4, 5e-4]
    init_type: truncated_normal
    init_scale: 0.3

    #data
    batch_size: 256
    dataset_type: c4

    #eval and logging

    log_gradients_and_weights: false
    decoding_interval: 0
    logging_interval_heavy: 1000
    eval_interval: 1000
    save_weights_interval: 0

    #fsdp
    fsdp_enabled: true
    fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
    fsdp_selective_precision_modules: "AttentionMechanism"

    #throughput
    mixed_precision: true
    mixed_precision_dtype: float16
    flash_attention: false
    gradient_accumulation_steps: 1
    loss_checkpoint_chungs: 8
