parent: configs/baselines/gpt/dense/mini.yaml
md5_parent_hash: bc3ba81ffd922aea064176ff5b0c1fad
time: 0-05:00:00

params:
  learning_rate: 1e-4
  torch_compile: true

  # init
  init_type: truncated_normal
  init_scale: 0.1
