parent: configs/baselines/gpt/dense/small.yaml
md5_parent_hash: 9bcdbfe14ff178e8ee90a04000ab9546
time: 0-10:00:00

params:
  learning_rate: 1e-4
  torch_compile: true

  # init
  init_type: truncated_normal
  init_scale: 0.1