parent: research/conditional/train/configs/baselines/gpt/dense/medium.yaml
md5_parent_hash: 7a0330388646a9bfbcbee67008f9538a
# singularity_image: /common/llm-random/images/sparsity_2023.12.14_16.44.42.sif
# singularity_image: /net/pr2/projects/plgrid/plggllmeffi/images/sparsity_2023.12.14_16.44.42.sif
singularity_image: /raid/NFS_SHARE/llm-random/images/sparsity_2023.12.14_16.44.42.sif
cuda_visible: "3"

time: "0-00:10:00"
# time: "00:20:00"

params:
  #tuning
  learning_rate: 1e-3
  load_balancing_loss_weight: 0.01 # wyjebać
  capacity_factor: 1.25 # literatoora

  #name
  name: mamba_moe
  tags: ["relu_vs_silu"]

  #mot
  ff_mode: vanilla

  # N_experts: 32 every expert size of normal DFF in vanilla

  n_experts: 32
  expert_size: 2048

  batch_size: 256
  # batch_size: 32
  # batch_size: 2
  # dataset_type: c4
  dataset_type: wikibook
  # use_dummy_dataset: false
  use_dummy_dataset: true

  #eval and logging
  log_gradients_and_weights: false
  decoding_interval: -1
  # logging_interval_heavy: 1000
  logging_interval_heavy: -1
  save_weights_interval: 0

  #fsdp
  fsdp_enabled: false
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  activation_checkpointing_modules: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: ["AttentionMechanism,ExpertGating"]
  grad_clip: 0.5

  #throughput
  mixed_precision: false
  mixed_precision_dtype: bfloat16
  flash_attention: false
  # gradient_accumulation_steps: 1 #!!!!!!!!!!!! THIS IS NONTRIVIAL
  loss_checkpoint_chungs: 0 # szymon ma 8
  init_type: truncated_normal
  init_scale: 0.1
  n_steps: 100_000

  #mamba

  dataset_type: wikibook
  use_dummy_dataset: true
  block_modules: ["attention", "feedforward"]
  no_positional_embedding: false
  # ^activation_type: ["relu", "silu"]
  ^activation_type: ["relu"]
  # num_workers: 8
