parent: research/conditional/train/configs/baselines/gpt/dense/medium.yaml
md5_parent_hash: 7a0330388646a9bfbcbee67008f9538a
interactive_debug: false
n_gpus: 1
cuda_visible: "6"
time: "00:10:00"
params:
    n_steps: 100
    #tuning
    ^learning_rate: [1e-3]
    load_balancing_loss_weight: 0.1
    capacity_factor: 1.0

    #name
    name: test-switch
    tags: [test-switch]

    #mot
    ff_mode: token_choice

    n_experts: 32
    expert_size: 2048

    #data
    batch_size: 256

    # fsdp
    # fsdp_enabled: false
    # fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
    # fsdp_selective_precision_modules: "AttentionMechanism"

    #throughput
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: false
    # gradient_accumulation_steps: 1
    loss_checkpoint_chungs: 8

    init_type: truncated_normal
    init_scale: 0.3

    # dataset_type: wikibook
    # use_dummy_dataset: true

    # LOCAL
    # batch_size: 3
    # n_blocks: 1
    # dmodel: 16
    # dataset_type: wikibook
    # use_dummy_dataset: true
    # fsdp_enabled: false
    # mixed_precision: false
