parent: research/conditional/train/configs/baselines/gpt/dense/medium.yaml
md5_parent_hash: 7a0330388646a9bfbcbee67008f9538a
interactive_debug: false
n_gpus: 1
cuda_visible: "6"
time: "00:10:00"
params:
    n_steps: 100
    #tuning
    ^learning_rate: [1e-3]
    load_balancing_loss_weight: 0.1 # wyjebać
    capacity_factor: 1.25 # literatoora

    #name
    name: test-switch
    tags: [test-switch]

    #mot
    ff_mode: token_choice
    # ff_mode: token_choice_deprecated

    # N_experts: 32 every expert size of normal DFF in vanilla

    n_experts: 32
    expert_size: 2048

    #data
    batch_size: 256
    # batch_size: 32
    # batch_size: 2
    # dataset_type: c4

    #eval and logging
    log_gradients_and_weights: false
    decoding_interval: 0
    # logging_interval_heavy: 1000
    # logging_interval_heavy: 20
    # logging_interval_light: 10
    logging_interval_heavy: 7
    logging_interval_light: 5
    eval_interval: 20
    save_weights_interval: 0

    #fsdp
    fsdp_enabled: false
    # fsdp_enabled: true
    fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
    fsdp_selective_precision_modules: "AttentionMechanism" # Routing + attention
    # activation_checkpointing_modules: "EmbeddingLayer,PredictionHead,TransformerBlock"

    #throughput
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: false
    # gradient_accumulation_steps: 1 #!!!!!!!!!!!! THIS IS NONTRIVIAL
    loss_checkpoint_chungs: 8 # szymon ma 8

    init_type: truncated_normal
    init_scale: 0.3

    dataset_type: wikibook
    use_dummy_dataset: true

    # LOCAL
    batch_size: 3
    # loss_checkpoint_chungs: 8
    # dataset_type: wikibook
    # use_dummy_dataset: true
    # fsdp_enabled: false
    # # gradient_accumulation_steps: 0
    # mixed_precision: false
    n_blocks: 1
    dmodel: 16
