parent: research/conditional/train/configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: 7f551916effeb9ba50a9aafa2f139b32
time: 7-00:00:00

params:
  name: "expert_choice_base"
  dmodel: 1024
  n_blocks: 24
  n_att_heads: 16

