parent: research/conditional/train/configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: 7f551916effeb9ba50a9aafa2f139b32
time: 1-00:00:00

params:
  name: "expert_choice_medium"
  dmodel: 512
  n_blocks: 8
  n_att_heads: 8
