parent: research/conditional/train/configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 7973e22f5f019acdc658ba4aa5bd4d39
time: 2-00:00:00

params:
  learning_rate: 1e-4
  torch_compile: true

  # init
  init_type: truncated_normal
  init_scale: 0.1