parent: research/conditional/train/configs/baselines/gpt/dense/large.yaml
md5_parent_hash: f302d0e1ac355da664d0ec06725ae6dc
time: 7-00:00:00

params:
  learning_rate: 1e-4
  torch_compile: true

  # init
  init_type: truncated_normal
  init_scale: 0.1
