parent: research/conditional/train/configs/baselines/gpt/dense/mini.yaml
md5_parent_hash: 18d960a81fbca975869c45f534745889
time: 0-05:00:00

params:
  learning_rate: 1e-4
  torch_compile: true

  # init
  init_type: truncated_normal
  init_scale: 0.1
