parent: research/conditional/train/configs/baselines/gpt/dense/small.yaml
md5_parent_hash: e59d582fde7b112cf31f8b8a5677295e
time: 0-10:00:00

params:
  learning_rate: 1e-4
  torch_compile: true

  # init
  init_type: truncated_normal
  init_scale: 0.1