# grid args
runner: "research.conditional.train.cc_train"
time: "2-00:00:00"
nodelist: "gpu01"
cuda_visible: "0"

# train params
params:
  # model
  batch_size: 512
  cutoff: 128
  project_name: "pmtest/llm-random"
  name: "softmax_grid"
  mixed_precision: true
  loss_checkpoint_chungs: 8
  tags:
    - "softmax_grid"
  use_neptune: true
  n_steps: 100000
  dmodel: 512
  dff: 2048
  n_blocks: 8
  n_att_heads: 8
  "^model_type":
    - "bert"
  "^ff_mode":
    - "expert_choice"
  "n_experts": 32
  "^total_experts_width":
    - 65536
  "^effective_dff":
    - 2048
  logging_interval_heavy: 5000
  every_other_layer: false
  logging_interval_loss: 1000
  grad_clip: 0.5
  lr_decay: 0.8
  lr_warmup_steps: 0
  lr_decay_interval: 10000
  group_granular_moe_by_batch: true
  "^granular_additional_norm":
    - "layer_norm"
    - "rezero"
    - "none"
  "^granular_normalize_token_update":
    - true
    - false
  "^softmax_over":
    - "experts"
    - "experts_tokens"
    - "tokens"




