parent: configs/baselines/gpt/mot/mini.yaml
md5_parent_hash: 05d3444cbe417fffee64fba32b1248d4


time: "00:30:00"

params:
  name: "gradient_checkpointing"
  gradient_checkpointing: true
  save_weights_interval: 1000
  logging_interval_heavy: 1000
  tags: ["cluster_test", "gradient_checkpointing"]
  n_steps: 5000