parent: configs/baselines/gpt/mot/mini.yaml
md5_parent_hash: 05d3444cbe417fffee64fba32b1248d4


time: "00:30:00"

params:
  name: "gradient_accumulation_steps_8"
  gradient_accumulation_steps: 8
  save_weights_interval: 0
  logging_interval_heavy: 1000
  tags: ["cluster_test", "gradient_accumulation_steps"]
  n_steps: 5000