runner: "research.attention_moe.train.train"
time: 08:00:00
n_gpus: 4
interactive_debug: false
backends_module: research.attention_moe.backends

# train params
params:
  name: "diff_gda_adapters_grid_fix"

  # base bass
  mixed_precision: true
  flash_attention: true

  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 1000
  logging_interval_light: 500
  logging_interval_loss: 1000
  save_weights_path: "model_ckpt"
  save_weights_interval: -1
  save_final_weights: true
  tags: ["diff_gda_adapters_grid_fix"]


  cutoff: 4096
  batch_size: 32
  n_steps: 45_000
  final_lr_step: 45_000
  scheduler: cosine
  lr_warmup_steps: 450
  final_lr_fraction: 0.1
  gradient_accumulation_steps: 1

  grad_clip: 1.0
  model_type: gpt
  dataset_type: c4
  # capacity_factor: 1.25
  weight_decay: 0.01
  # topk: 1

  # model
  use_rope: true
  ff_mode: swi_glu
  ^attention_mode: [
#     "diff_vanilla_fast1",
    "diff_theirs_fast1"
  ]
  ^dmodel: [768]
#  dff: 3072
  ^dff: [1998]
  n_blocks: 12
  n_att_heads: 12
  ^n_negative_heads: [2]
  ^learning_rate: [5e-4, 1e-3, 2e-3]
  data_seed: 42
  init_type: truncated_normal
  init_scale: 0.1
  mixed_precision_dtype: bfloat16
  ^diff_transformer_lowrank_dim: [64]
  ^diff_transformer_negative_heads_permutation: [repeat, interleave, roll_repeat, repeat_roll, roll_interleave]
#  ^diff_transformer_adapter_type: [additive, multiplicative, lora, identity, multiadd]
  ^diff_transformer_adapter_type: [lora]
  use_qk_norm: true
  evaluate_attention_relevancy_interval: 5000
  # ^load_balancing_loss_weight: [0.01]

  # fsdp
  fsdp_enabled: true
  fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
  fsdp_selective_precision_modules: "AttentionMechanism,RoPE"
  torch_compile: false
