parent: configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: 27e0212d49a74700ba49088f6410580d
time: 2-00:00:00

params:
  name: "expert_choice_base"
  dmodel: 768
  n_blocks: 12
  n_att_heads: 12
