parent: configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: c8fa324536a6964908602dd6aa8796d4
time: 1-00:00:00

params:
  name: "expert_choice_medium"
  dmodel: 512
  n_blocks: 8
  n_att_heads: 8
