parent: research/conditional/train/configs/baselines/gpt/small.yaml
md5_parent_hash: cbdf4e5992f41713488c25c819086e51
time: "0-20:10:00"

params:
  name: blanx-small-grid
  learning_rate: 1e-3
  n_steps: 100000

  # blanx args
  ^n_blanks: [1]
  ^blanks_residual: [true]
  ^blanks_add_embedding: [true, false]
  tokenizer: gpt

  # n_blocks: 4

  # LOCAL:
  batch_size: 2
  use_dummy_dataset: true
  num_workers: 0
