scalings:
  - name: "Granular"
    tags:
      - "fixed_grid_wd"
    power_laws:
      - - "n_params"
      - - "granularity"
      - - "n_steps"
      - - "granularity"
        - "n_params"
      - - "granularity"
        - "n_steps"
    plot_dims:
    - - "flops"
      - "n_params"
      - "n_steps"
#    - - "flops"
#      - "n_params"
#    - - "flops"
#      - "n_steps"
#    - - "granularity"
#    - - "n_steps"
#    - - "n_params"
project_name: "pmtest/llm-random"
num_opt_steps: 100000