scalings:
  - name: "dense_4"
    tags:
      - "zubr_dense_grid"
    fixed:
      expansion_rate: 1
      granularity: 0
    power_laws:
      - - "n_params"
      - - "n_steps"
    use_chinchilla: true
    num_opt_steps: 100000
    lr: 0.01
    final_lr_fr: 0.01
    cmap: copper
  - name: "Granular_18"
    tags:
      - "fixed_grid_wd"
    tags_negative:
      - "gran_grid_failed"
      - "lr_steps_bug"
    fixed:
      expansion_rate: 64
    power_laws:
      - - "granularity"
      - - "n_params"
        - "granularity"
      - - "n_steps"
        - "granularity"
    use_chinchilla: true
    exp_inter: false
    poly_inter: true
    num_opt_steps: 100000
    lr: 0.01
    final_lr_fr: 0.01
    cmap: rainbow
plot_dims:
#  - - "predicted_loss"
#    - "granularity"
#  - - "predicted_loss"
#    - "n_steps"
  - - "predicted_loss"
    - "n_params"
  - - "flops"
    - "n_params"
    - "n_steps"
#  - - "flops"
#    - "n_steps"
#  - - "flops"
#    - "n_params"
  - - "granularity"
#  - - "n_steps"
#  - - "n_params"
extrapolate_factor: 4.0
use_scipy: true
load_model: false
opt_log_loss: false
huber_delta: 0.001
weight_decay: 0.000001
show_model_sizes:
  10M: 10e6
  100M: 100e6
  500M: 500e6
  1B: 1e9
  3B: 3e9
  7B: 7e9
  70B: 70e9
  500B: 500e9
  1T: 1e12
plot_points: 100
project_name: "pmtest/llm-random"