parent: research/conditional/train/configs/baselines/gpt/mini.yaml
md5_parent_hash: 019212718f2ace8645ddca8f28f6eaee
name: saturation_test_mini_ch
time: 0-05:00:00
n_gpus: 1

params:
  # technical/common params
  name: saturation_test_mini_ch
  ff_mode: expert_choice
  softmax_over: experts
  group_granular_moe_by_batch: true
  use_full_einsum: true
  granular_moe_one_hot_impl: true
  flash_attention: true
  logging_interval_heavy: 1_000_000
  loss_checkpoint_chungs: 8
  decoding_interval: 0

  # init
  init_type: truncated_normal
  init_scale: 0.1

  # params of expert choice
  total_experts_width: 32768
  ^effective_dff: [768, 1024, 1536]
  n_experts: 128

  # ------ FILL IN BELOW ------
  n_steps: 50_000
  scheduler: cosine
  learning_rate: 1e-4
  lr_warmup_steps: 5000
  final_lr_step: 50_000
  batch_size: 256
  cutoff: 256
